name: Installation Issues
description: Use this template for reporting bugs encountered while installing MLflow.
labels: 'bug'
title: '[SETUP-BUG]'

body:
  - type: markdown
    attributes:
      value: |
        We encourage submitting an issue directly to [MLFlow](https://github.com/mlflow/mlflow/issues/new?assignees=&labels=bug&template=installation_issue_template.yaml&title=%5BSETUP-BUG%5D)
